### ISSUE TITLE
Define thumbnail layout for different types

### ISSUE THREAD

**Issue by jmarsh24** [jmarsh24/tangocloud#326]
We currently have featured playlists. 

Best of Pugliese
  - Editor's Choice

Pugliese Essentials

(DJ Set)
Oct 27, 2024
Milonga La Coqueta

We should explore different options on how to display the different playlists.

![Image](https://github.com/user-attachments/assets/38a42e13-747d-4f68-82d2-fe8416f78612)

It's possible that we need to modify the data model to incorporate more fields. We should explore adding badges, various rows of information, etc.

**Acceptance Criteria**

- DJ Set Layout
- best songs of orchestra
- essential songs
- User generated playlists
- Specialized thumbnails generated for the essentials playlists.
- anymore?

- Figma or photoshop mockups of the different options

**Comment by jmarsh24** [comment]
![Image](https://github.com/user-attachments/assets/f65e1cbc-3ffd-4e96-a7c2-9ea6036672d7)
![Image](https://github.com/user-attachments/assets/2214c827-8d43-4fb7-a4f1-8a99bf4bb2e2)
![Image](https://github.com/user-attachments/assets/29de6966-c9a4-48cf-bb87-4ef5290cadcb)

**Comment by eleonorapopovska** [comment]
![Image](https://github.com/user-attachments/assets/e9773add-cef5-4c63-a2d4-62e9a7e3b83c)

This is my suggestion on organising the **playlist thumbnails layout** for now, the link to the Figma file, look inside the page called Playlist Thumbnails Lab, link is here >>> 

https://www.figma.com/design/nJqc9ztwDs8ce0wdE2a4Q5/TangoCloud_2024?node-id=512-28586&t=ZOjVfOkCZVu9hcti-1

**Comment by eleonorapopovska** [comment]
I chose Monserrat as the font mainly because it’s similar to Circular, which we had before, but it’s a Google Webfont. As seen in Dogac’s screenshots on other issues, seems like he doesn’t have it as a system font, so the typography looks different for him. To ensure it looks the same for everyone out there, we want to use a webfont instead of a system font. More guidelines on typography coming soon.

**Comment by jmarsh24** [comment]
One thing to keep in mind when doing any type of thumbnail is that you should consider what this looks like if you have an extremely long title or subtitle. A developer needs to know if the lines will wrap into multiple lines. show an elipsis... how long  should it go until it turns into an ellipsis, etc. 

This can appear on mobile where the playlist will take up 1 whole row? or 2 rows? Does it behave differently there?

**Comment by eleonorapopovska** [comment]
Why does the displayed typography look different in D's screenshots?

![Image](https://github.com/user-attachments/assets/965f8679-5760-4f00-a7a7-9858d7b8949f)
![Image](https://github.com/user-attachments/assets/69f8ba7f-762c-424b-b7f6-eb51f48991b5)

**Comment by eleonorapopovska** [comment]
This is actually a point I was hoping we avoid. What you’re asking for is essentially a Design Style Guide, which is typically one of the final steps in preparing for development. It comes after completing the design process and includes all components, their variations, color styles, typography styles, and design guidelines laid out as part of the project documentation. :)

<img width="778" alt="Screenshot 2024-11-15 at 18 40 50" src="https://github.com/user-attachments/assets/40b9c6d5-7167-41a5-9923-1aaf4cf514b4">

The task belongs to the end of UI development, and so does it's solution. By solving it now, we are starting the process from the back end, trying to figure out a High-Fi definition solution of a problem that might not exist in the next version for Tango Cloud, because maybe we won't even have this type of thumbnails for the playlists there anymore. 
We're not at a point where we should be in detail discussing it, as we are skipping vital steps. However, I am trying to give you guys feedback and support, that you might find useful until this Sunday the 17th of November and keep us constructive and still on the same page as much as possible. 

<img width="1680" alt="Screenshot 2024-11-15 at 18 53 39" src="https://github.com/user-attachments/assets/e0f740c6-468d-400a-b49c-e5b471b45ba2">
<img width="1680" alt="Screenshot 2024-11-15 at 19 16 29" src="https://github.com/user-attachments/assets/a507e706-1eb6-4204-acb3-29353f5dff68">

This is what I have thought about: I have opened the grids in Figma so that you can see, that the Thumbnail is based on a 8px grid, with 8px margins for the text on all sides, 16px between the image and the text. The corner radius of the component is 12. Everything we design should be responsive, so the constraints are set to scale. If I try to type in more text, the field can fit in 4 rows of text if necessary, by Autolayout. That is as far as I got today. I hope it helps.

**Comment by eleonorapopovska** [comment]
This was the small change I suggest in the Orchestra Cards, regarding the image placement/margins. And having the same layout principle as the other Thumbnails as base. 

![Image](https://github.com/user-attachments/assets/38a216ff-981f-428e-95c7-6d0378dab701)

**Comment by eleonorapopovska** [comment]
For the Recordings Thumbnail, it's interesting that you've already implemented it, before I could post it... and the only difference is, I thought the heat rating, or any badge, or icon, or tag that will come in the future, should be aligned bottom, right- to not collide with the text field.

![Image](https://github.com/user-attachments/assets/b2e812b7-711b-497f-9e9e-cc193b741a4e)
